backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Page Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Image Alt Text, name: imageAlt, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Hero CTA Title, name: heroCTATitle, widget: string }
          - { label: Hero CTA Link, name: heroCTALink, widget: string }
          - { label: Brand Logo 1, name: brandLogo1, widget: image }
          - { label: Brand Logo 2, name: brandLogo2, widget: image }
          - { label: Brand Logo 3, name: brandLogo3, widget: image }
          - { label: Brand Logo 4, name: brandLogo4, widget: image }
          - { label: Brand Logo 5, name: brandLogo5, widget: image }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  { label: Column 1 Text, name: col1, widget: text },
                  { label: Column 2 Text, name: col2, widget: text },
                  { label: CTA Title, name: ctaTitle, widget: string },
                  { label: CTA Link, name: ctaLink, widget: string },
                  { label: Color, name: color, widget: select, options: ["lightblue"]},
                  { label: Add Image, name: imageOption, widget: select, options: ["no-image"]}
                ],
            }
          - { 
              label: Partner Showcase,
              name: partners,
              widget: object,
              fields:
              [
                { label: Partner Logo 1, name: partnerLogo1, widget: image },
                { label: Partner Logo 2, name: partnerLogo2, widget: image },
                { label: Partner Logo 3, name: partnerLogo3, widget: image },
                { label: Partner Logo 4, name: partnerLogo4, widget: image },
                { label: Partner Logo 5, name: partnerLogo5, widget: image },
              ]
            }
          - {
              label: About Us Preview,
              name: about,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }